# Generated by Django 5.2.12 on 2026-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menus',
            field=models.ManyToManyField(related_name='restaurant_menus', to='restaurants.menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(blank=True, choices=[(1, '€'), (2, '€€'), (3, '€€€')], default=1),
        ),
    ]
