# Generated by Django 5.2.12 on 2026-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_category_id_alter_restaurant_id_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='capacity',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(blank=True, choices=[(1, '€'), (2, '€€'), (3, '€€€')], default=2),
            preserve_default=False,
        ),
    ]
