# Generated by Django 5.2.12 on 2026-03-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_menucategory_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.menuitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories1', to='restaurants.menuitem'),
            preserve_default=False,
        ),
    ]
