# Generated by Django 5.2.12 on 2026-03-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_menuitem_category_remove_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucategory',
            old_name='menu_category',
            new_name='menu_item',
        ),
    ]
