# Generated by Django 5.2.12 on 2026-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_review_parent_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3),
        ),
    ]
