# Generated by Django 5.2.12 on 2026-05-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_city_alter_restaurant_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
    ]
