# Generated by Django 6.0.2 on 2026-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_category_id_alter_city_id_alter_favorite_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='time',
            field=models.ManyToManyField(related_name='restaurant_openhours', to='restaurants.openinghours'),
        ),
    ]
