# Generated by Django 6.0.2 on 2026-05-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_remove_menu_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name_plural': 'Opening Hours'},
        ),
    ]
