# Generated by Django 6.0.2 on 2026-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_openinghours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='currency',
            field=models.CharField(choices=[('TRY', 'TL'), ('USD', 'Dolar'), ('EUR', 'Euro')], default='TRY', max_length=3),
        ),
    ]
