# Generated by Django 5.2.12 on 2026-05-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_menu_category_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
            preserve_default=False,
        ),
    ]
