# Generated by Django 5.2.12 on 2026-05-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_reviewlike_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlike',
            name='value',
            field=models.IntegerField(),
        ),
    ]
